name: ansible-lint
on:
  push:
      branches:
        - main
      paths-ignore:
        - .gitignore
        - README.md
        - LICENSE
  pull_request:
      branches:
        - main
      paths-ignore:
        - .gitignore
        - README.md
        - LICENSE

jobs:
  build:
    name: ansible lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@main
        with:
          path: "ansible/"
